# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb2a973a641ca3ace8fe89cf9089ee7f07d7cd88a16b2ab8b30d225f419363c474d4a16799134e51d00658d744317cb0d9db6099810da3ca453c6acd2232723

test:
  secret_key_base: 909e344384ccd8ac31e7d336f80cd07e5fe9795042f122b8d5fb6c5f52f0a86f538bb431e7e92c1329cb1d3193763a55be52f73cee088f26c5eb6e2a857191da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
